spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/db_management?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username:  root
    password:  zhangjun249