spring:
  application:
    name: gateway
  profiles:
    active: dev
  #  zipkin:
  #    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1

server:
  port: 8761


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/