eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

server:
  port: 8762

spring:
  application:
    name: service-auth-management


  datasource:
    url:  jdbc:mysql://localhost:3306/db_management?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username:  root
    password:  zhangjun249
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 127.0.0.1
    port: 6379

auth:
  security:
    oauth2:
      jwtSigningKey: billow
    client:
      client-id: app
      client-secret: app
      grant-type: password
      access-token-uri: http://127.0.0.1:${server.port}/oauth/token