eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

server:
  port: 8763

spring:
  application:
    name: service-organization-management

  datasource:
    url:  jdbc:mysql://localhost:3306/db_management?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username:  root
    password:  zhangjun249

security:
  oauth2:
    resource:
      user-info-uri: http://service-zuul/uaa/user
      loadBalanced: true